window.QUESTION_BANK = {
    phase1: [
        { q: "Quelle est la seule planète du Système solaire à avoir été découverte par des calculs mathématiques avant même d'être observée au télescope ?", a: "Neptune", d: "C'est l'astronome français Urbain Le Verrier qui a déduit sa position en étudiant les anomalies de l'orbite d'Uranus. On théorise qu'il y pleut des diamants !", pts: 1 },
        { q: "Quelle catégorie de corps célestes a été créée en 2006, entraînant le déclassement de Pluton ?", a: "Les planètes naines", d: "En plus de la taille, être une planète nécessite d'avoir fait le ménage dans son orbite, ce qui n'est pas le cas de Pluton ou Cérès.", pts: 1 },
        { q: "Quelle force régit le mouvement des planètes autour du Soleil ?", a: "La gravitation", d: "Théorisée par Isaac Newton en 1687, elle sera plus tard expliquée par Albert Einstein comme une déformation de l'espace-temps.", pts: 1 },
        { q: "Comment appelle-t-on une planète qui orbite autour d'une autre étoile ?", a: "Une exoplanète", d: "La toute première (51 Pegasi b) a été découverte en 1995 par deux astronomes suisses, Michel Mayor et Didier Queloz, ce qui leur a valu le prix Nobel en 2019 !", pts: 1 },
        { q: "Entre les orbites de quelles planètes se trouve la ceinture principale d'astéroïdes ?", a: "Entre Mars et Jupiter", d: "Elle contient des millions de fragments rocheux qui n'ont jamais pu former une planète, en particulier à cause de la force de gravité titanesque de Jupiter. On y trouve la planète naine Cérès.", pts: 1 },
        
        { q: "Quelle est le nom de l'énorme tempête anticyclonique que l'on peut observer sur Jupiter ?", a: "La Grande Tache rouge", d: "Elle est observée depuis plusieurs siècles et est si gigantesque que l'on pourrait y faire entrer la Terre entière.", pts: 2 },
        { q: "Quelle unité de mesure représente la distance Soleil-Terre ?", a: "L'unité astronomique", d: "Elle équivaut à environ 150 000 000 km. Pour ordre de grandeur, Neptune se situe à 30 UA et le nuage d'Oort s'étend jusqu'à 100 000 UA.", pts: 2 },
        { q: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", a: "Environ 8 minutes", d: "La lumière voyageant à environ 300 000 km/s, si le Soleil disparaissait, nous ne le saurions que 8 minutes plus tard.", pts: 2 },
        { q: "Quel effet physique permet de déduire que l'Univers est en expansion grâce au décalage vers le rouge des galaxies ?", a: "L'effet Doppler (ou Doppler-Fizeau)", d: "C'est le même principe qui rend le son de la sirène d'une ambulance plus grave lorsqu'elle s'éloigne de nous.", pts: 2 },
        { q: "Comment se nomme la limite autour d'un trou noir au-delà de laquelle rien ne peut s'échapper ?", a: "L'horizon des événements", d: "Une fois cette frontière franchie, la vitesse de libération devient supérieure à la vitesse de la lumière.", pts: 2 },
        
        { q: "Comment appelle-t-on le type d'étoile extrêmement dense et tournant très vite sur elle-même ?", a: "Un pulsar (ou étoile à neutrons)", d: "La matière d'une étoile à neutrons est si condensée qu'elle a près de 2 fois la masse du soleil dans une sphère de 20 km. Le premier pulsar a été découvert par Jocelyn Bell pendant sa thèse.", pts: 3 },
        { q: "Lorsqu'une étoile massive arrive en fin de vie, la création de quel élément chimique dans son cœur précipite son explosion en supernova ?", a: "Le fer", d: "Contrairement aux éléments plus légers, la fusion du fer consomme plus d'énergie qu'elle n'en produit. Sans énergie pour contrer la gravité, l'étoile s'effondre sur elle-même.", pts: 3 },
        { q: "Quel effet optique, prédit par Albert Einstein, est causé par la courbure de l'espace-temps autour d'un amas massif déviant la lumière d'une galaxie d'arrière-plan ?", a: "Une lentille gravitationnelle", d: "Cet effet agit comme une loupe cosmique, permettant aux astronomes de voir des objets situés beaucoup plus loin.", pts: 3 },
        { q: "Comment appelle-t-on la limite de masse au-delà de laquelle une naine blanche s'effondre sous sa propre gravité ?", a: "La limite de Chandrasekhar", d: "En dessous de cette masse, la naine blanche reste stable. Au-dessus, elle explose en supernova de type Ia ou s'effondre en étoile à neutrons.", pts: 3 },
        { q: "L'axe de rotation de la Terre tourne lentement sur lui-même comme une toupie, bouclant un cycle en 26 000 ans. Comment appelle-t-on ce phénomène ?", a: "La précession", d: "C'est à cause de ce mouvement que notre pôle Nord céleste se déplace. Dans environ 12 000 ans, c'est la brillante étoile Véga qui remplacera notre Étoile polaire actuelle !", pts: 3 }
    ],
phase2: {
        "Le système solaire": [
            { q: "Quelle planète est surnommée la planète rouge à cause de l'oxyde de fer (rouille) à sa surface ?", a: "Mars", d: "Planète ayant potentiellement abritée de l'au liquide à sa surface, il y fait maintenant très froid avec une moyenne de -63°C à l'équateur.", pts: 1 },
            { q: "Quelle planète est célèbre pour son système d'anneaux très brillant et visible, principalement composé de glace et de roche ?", a: "Saturne", d: "Ses anneaux sont si fins par rapport à leur largeurs (quelques dizaines de mètres d'épaisseur pour ~400 000km de large) que, vus de la tranche, ils disparaissent presque complètement.", pts: 1 },
            { q: "Contrairement aux autres planètes, quelle planète tourne sur elle-même dans le sens inverse (d'est en ouest) ?", a: "Vénus", d: "Sur Vénus, le Soleil se lève à l'ouest et se couche à l'est. Elle tourne aussi si lentement qu'une journée est plus longue qu'une année (224 jours pour tourner autour du soleil mais 243 pour tourner autour d'elle même) !", pts: 2 },
            { q: "Quel gaz compose majoritairement le Soleil ?", a: "L'hydrogène", d: "Le Soleil est composé d'environ 73% d'hydrogène et 25% d'hélium. C'est la fusion de l'hydrogène en hélium qui produit son énergie.", pts: 2 },
            { q: "Comment appelle-t-on la limite de la sphère d'influence du vent solaire, là où il s'arrête face au milieu interstellaire ?", a: "L'héliopause", d: "Néanmoins elle ne marque pas forcément la frontière du système solaire, en effet après l'héliopose (située à environ 120 UA) se trouverai le nuage d'Oort, un nuage hypothétique composé de milliards de corps glacés, il s'étendrai de 2000 UA jusqu'à 50 000 à 100 000 UA.", pts: 3 }
        ],
        "Lunes, Astéroïdes et Comètes": [
            { q: "Entre les orbites de quelles planètes se trouve la ceinture principale d'astéroïdes ?", a: "Entre Mars et Jupiter", d: "Elle contient des millions de fragments rocheux qui n'ont jamais pu former une planète, en particulier à cause de la gravité de Jupiter.", pts: 1 },
            { q: "Quelle est la principale différence de composition entre un astéroïde et une comète ?", a: "La comète contient de la glace", d: "C'est en partie cette glace qui, en se sublimant à l'approche du Soleil, forme la célèbre chevelure et la queue des comètes.", pts: 1 },
            { q: "Quelle est la plus grande lune du Système solaire ?", a: "Ganymède", d: "Ce satellite de Jupiter est plus grand que la planète Mercure. C'est aussi la seule lune connue à posséder son propre champ magnétique.", pts: 2 },
            { q: "Comment s'appelle le grand anneau de corps glacés situé au-delà de l'orbite de Neptune ?", a: "La ceinture de Kuiper", d: "Elle est similaire à la ceinture d'astéroïdes mais 20 fois plus large, et contient également les restes de la formation du Système solaire. On y trouve de nombreuses planètes naines comme Pluton ou Eris", pts: 2 },
            { q: "En astronomie, qu'est-ce qu'un astéroïde troyen ?", a: "Un astéroïde qui partage la même orbite qu'une planète", d: "Ils sont piégés dans les points de Lagrange L4 et L5 (zones de stabilité gravitationnelle) en avant ou en arrière de la planète. Les plus connus sont ceux de Jupiter qui en possède des milliers, mais la Terre en possède également 2 connus à ce jour.", pts: 3 }
        ],
        "Exoplanètes et Astrobiologie": [
            { q: "Comment appelle-t-on une planète qui tourne autour d'une autre étoile ?", a: "Une exoplanète", d: "La toute première a été découverte en 1995 par les astronomes suisses Michel Mayor et Didier Queloz. Elle orbite autour de l'étoile 51 Pegasi b.", pts: 1 },
            { q: "Comment s'appelle la zone théorique autour d'une étoile où la température permettrait d'avoir de l'eau liquide ?", a: "La zone habitable", d: "Être dans cette zone ne garantit pas la vie (la Lune y est, mais n'a pas d'eau liquide), mais c'est un très bon point de départ pour les recherches d'eau liquide et donc, de potentielles formes de vie.", pts: 1 },
            { q: "Quelle méthode est la méthode de détection d'exoplanète la plus efficace à ce jour ?", a: "La méthode des transits", d: "Elle consiste à observer les faibles baisses de luminosité de l'étoile quand la planète passe devant.", pts: 2 },
            { q: "Quel petit animal microscopique terrestre est célèbre pour sa capacité à survivre dans le vide de l'espace ?", a: "Le tardigrade", d: "Il peut se déshydrater presque totalement, ralentir très fortement son métabolisme et remplacer ses cellules pour résister au vide, aux radiations et aux températures extrêmes. Cet état est appelé Cryptobiose", pts: 2 },
            { q: "Quel système planétaire, situé à environ 40 années-lumière, est devenu célèbre pour abriter 7 planètes de taille terrestre, dont 3 en zone habitable ?", a: "TRAPPIST-1", d: "Elles orbitent autour d'une étoile naine rouge ultra-froide, et sont l'une des cibles principales du télescope James Webb.", pts: 3 }
        ], 
        "Étoiles et Constellations": [
            { q: "Comment s'appelle l'étoile qui indique toujours le nord dans l'hémisphère nord ?", a: "L'étoile polaire", d: "Elle ne bouge pas car elle est située presque exactement dans le prolongement de l'axe de rotation de la Terre.", pts: 1 },
            { q: "Quelle constellation est célèbre pour sa forme de grande Casserole ?", a: "La Grande Ourse", d: "La casserole, composée de 7 étoiles, n'est en fait qu'une partie (un astérisme) de la constellation complète.", pts: 1 },
            { q: "Quel nom donne-t-on aux trois étoiles alignées qui forment la ceinture de la constellation d'Orion ?", a: "Les Trois Rois (ou les trois mages)", d: "Leurs véritables noms astronomiques sont Alnitak, Alnilam et Mintaka.", pts: 2 },
            { q: "A quelle distance du soleil se trouve Proxima du Centaure, l'étoile la plus proche du soleil ?", a: "~4,2 années-lumières", d: "Elle est située à environ 4,2 années-lumière. Malgré sa proximité spatiale, c'est une naine rouge impossible à voir à l'œil nu.", pts: 2 },
            { q: "Dans le classment des étoiles par type spectral (O, B, A, F, G, K, M), à quelle catégorie appartient notre Soleil ?", a: "Le type G (Naine jaune)", d: "Les étoiles O sont les plus chaudes et bleues, tandis que les M sont les plus froides et rouges. Le Soleil est une étoile moyenne de type G2V.", pts: 3 }
        ],
        "Ciel profond": [
            { q: "Quel est le nom de la galaxie spirale dans laquelle nous nous trouvons ?", a: "La Voie lactée", d: "Vue de la Terre depuis un ciel très sombre, elle ressemble à une traînée de lait étalée dans le ciel, d'où son nom.", pts: 1 },
            { q: "Comment appelle-t-on l'explosion gigantesque qui marque la fin de vie d'une étoile massive ?", a: "Une supernova", d: "Durant cette explosion, l'étoile peut briller temporairement plus fort que toutes les autres étoiles de sa galaxie réunies.", pts: 1 },
            { q: "Comment se nomme la limite immatérielle autour d'un trou noir au-delà de laquelle rien ne peut s'échapper, même la lumière ?", a: "L'horizon des événements", d: "Une fois cette frontière franchie, la vitesse de libération devient supérieure à la vitesse de la lumière (environ 300 000 km/s).", pts: 2 },
            { q: "Avec quelle galaxie voisine la Voie lactée va-t-elle fusionner dans environ 4 milliards d'années ?", a: "La galaxie d'Andromède (ou M31)", d: "C'est l'objet le plus lointain observable à l'œil nu depuis la Terre.", pts: 2 },
            { q: "Comment appelle-t-on la toute première lumière émise par l'Univers, encore détectable aujourd'hui sous forme de micro-ondes ?", a: "Le fond diffus cosmologique (ou rayonnement fossile)", d: "C'est l'écho du Big Bang, émis environ 380 000 ans après la naissance de l'Univers lorsque celui-ci est devenu transparent.", pts: 3 }
        ],
        "Mécanique Céleste et Phénomènes": [
            { q: "Lors d'une éclipse solaire, quel astre vient se placer exactement entre la Terre et le Soleil ?", a: "La Lune", d: "Le hasard fait que la Lune est 400 fois plus petite que le Soleil, mais aussi 400 fois plus proche, ce qui leur donne la même taille apparente.", pts: 1 },
            { q: "Qu'est-ce qu'une étoile filante en réalité ?", a: "Un débris rocheux qui brûle dans l'atmosphère (météore)", d: "La friction extrême avec l'air à haute vitesse vaporise l'astéroïde, créant la traînée lumineuse que l'on appelle un météore.", pts: 1 },
            { q: "Quel astre est le principal responsable du phénomène des marées océaniques sur Terre ?", a: "La Lune", d: "Son attraction gravitationnelle tire les océans, créant des bosses d'eau qui parcourent le globe avec la rotation terrestre, créant les marées hautes.", pts: 2 },
            { q: "Comment appelle-t-on le point de l'orbite où la Terre est la plus proche du soleil ?", a: "Le périhélie", d: "Paradoxalement pour nous, la Terre passe au périhélie au début du mois de janvier ! Cela prouve bien que la distance Terre-Soleil n'est pas ce qui crée les saisons, c'est l'inclinaison de la Terre.", pts: 2 },
            { q: "Qu'est-ce qui provoque les aurores boréales et australes sur Terre ?", a: "Les particules du vent solaire déviées par le champ magnétique", d: "Le bouclier magnétique terrestre ramène ces particules chargées vers les pôles, où elles ionisent les gaz de notre atmosphère qui se mettent à briller.", pts: 3 }
        ],
        "Matériel et Astrophotographie": [ 
            { q: "Comment s'appelle le célèbre télescope spatial de la NASA lancé en 1990 ?", a: "Hubble", d: "Il a offert des images historiques car, étant dans l'espace, il n'est pas gêné par les perturbations de l'atmosphère terrestre.", pts: 1 },
            { q: "Quelle est la différence fondamentale de conception entre une lunette astronomique et un télescope ?", a: "La lunette utilise des lentilles, le télescope des miroirs", d: "Les lunettes fonctionnent par réfraction de la lumière, tandis que les télescopes fonctionnent par réflexion.", pts: 1 },
            { q: "Quel type de monture mécanique permet de suivre facilement un astre en compensant la rotation de la Terre ?", a: "La monture équatoriale", d: "Une fois alignée avec l'étoile polaire, il suffit de tourner un seul axe pour annuler le mouvement du ciel.", pts: 2 },
            { q: "En optique, que calcule-t-on en divisant la longueur focale par le diamètre de l'instrument ?", a: "Le rapport F/D (rapport d'ouverture)", d: "Un rapport F/D court (ex: f/4) est très « lumineux » et adapté au ciel profond, un long (f/10) est souvent utilisé pour le planétaire.", pts: 2 },
            { q: "Dans une lunette de mauvaise qualité, quel nom donne-t-on aux halos colorés baveux autour des étoiles ?", a: "L'aberration chromatique", d: "Les lentilles simples ne focalisent pas toutes les couleurs exactement au même endroit. On corrige cela avec des objectifs dits apochromatiques.", pts: 3 }
        ],
        "Missions Historiques": [
            { q: "En quelle année ont eu lieu les premiers pas de l'Homme sur la Lune avec Apollo 11 ?", a: "1969", d: "Neil Armstrong et Buzz Aldrin ont marché sur la surface lunaire, pendant que Michael Collins restait en orbite.", pts: 1 },
            { q: "Qui est le tout premier être humain à être allé dans l'espace ?", a: "Youri Gagarine", d: "Le cosmonaute soviétique a décollé à bord de la capsule Vostok 1 en 1961 et a fait un tour de la Terre.", pts: 1 },
            { q: "Comment s'appelait le premier satellite artificiel français ?", a: "Asterix", d: "Lancé le 26 novembre 1965 il fait de la France le 3ème pays à envoyer un satellite en orbite par ses propres moyens.", pts: 2 },
            { q: "Qui fut la première femme à voler dans l'espace en 1963 ?", a: "Valentina Terechkova", d: "Cette cosmonaute soviétique a effectué 48 orbites autour de la Terre à bord de Vostok 6.", pts: 2 },
            { q: "Quel programme spatial a réussi, dans les années 70 et 80, à poser les seules et uniques sondes sur la surface infernale de Vénus ?", a: "Le programme Venera (Union Soviétique)", d: "Malgré 460°C et une pression écrasante, ces sondes ont survécu jusqu'à 2 heures et envoyé les seules photos du sol vénusien.", pts: 3 }
        ],
        "Missions Modernes": [
            { q: "Quelle mission, en collaboration entre la JAXA, le CNES et la DLR, part explorer les lunes de Mars en octobre 2026 ?", a: "MMX (Marian Moons eXploration)", d: "Son décollage est prévu pour le 19 octobre à 21h41 (heure de Paris). Il transportera un petit rover nommé Idefix !", pts: 1 },
            { q: "Quel nouveau télescope spatial, reconnaissable à son miroir en nid d'abeille, a été lancé fin 2021 ?", a: "Le James Webb Space Telescope (JWST)", d: "Spécialisé dans l'infrarouge, il est spécialisé dans la recherche d'anciennes galaxies, la formation d'étoiles, les exoplanètes et l'évolution des galaxies.", pts: 1 },
            { q: "Quelle sonde de la NASA a exploré la planète Saturne et ses anneaux de 2004 à 2017 ?", a: "Cassini", d: "La sonde a fini sa mission en plongeant dans l'atmosphère de Saturne pour éviter de s'écraser sur une lune potentiellement habitable comme Encelade.", pts: 2 },
            { q: "Comment s'appelle le petit hélicoptère de la NASA qui a réussi le premier vol motorisé sur une autre planète (Mars) en 2021 ?", a: "Ingenuity", d: "Prévu pour 5 vols de test, ce formidable petit engin en a finalement fait 72 avant d'endommager ses pales !", pts: 2 },
            { q: "Quelle sonde européenne a réalisé l'exploit de se placer en orbite autour de la comète Tchouri en 2014 et d'y lâcher l'atterrisseur Philae ?", a: "Rosetta", d: "Elle a prouvé, entre autres, que l'eau des comètes comme Tchouri n'a pas la même signature chimique que l'eau des océans terrestres.", pts: 3 }
        ],
        "Histoire de l'astronomie": [
            { q: "Quel physicien a formulé en 1687 la loi de la gravitation universelle ?", a: "Isaac Newton", d: "🍎⬇️", pts: 1 },
            { q: "Quel savant italien a braqué pour la première fois une lunette astronomique en 1609 ?", a: "Galilée", d: "Il y a découvert les cratères de la Lune, les taches solaires et les 4 grosses lunes de Jupiter (Io, Europe, Ganymède, Callisto).", pts: 1 },
            { q: "Qui a formulé mathématiquement la théorie de l'héliocentrisme (la Terre tourne autour du Soleil) en 1543 ?", a: "Nicolas Copernic", d: "Son ouvrage a révolutionné la science, bien qu'il ait repoussé sa publication jusqu'à la fin de sa vie par peur des représailles.", pts: 2 },
            { q: "Quel mathématicien allemand a découvert que les orbites des planètes ne sont pas des cercles parfaits, mais des ellipses ?", a: "Johannes Kepler", d: "Ses fameuses trois lois de Kepler sont toujours utilisées aujourd'hui pour calculer les orbites.", pts: 2 },
            { q: "Quelle astronome américaine a apporté les premières preuves de l'existence de la matière noire ?", a: "Vera Rubin", d: "En étudiant la vitesse de rotation des galaxies, elle a compris qu'elles contenaient beaucoup plus de matière que ce qu'on pouvait observer.", pts: 3 }
        ],
        "Mythes et Légendes du ciel": [
            { q: "Dans la mythologie romaine, Jupiter est le roi des dieux. Quel est son nom dans la mythologie grecque ?", a: "Zeus", d: "C'est le dieu du ciel et de la foudre et le roi de l'Olympe, un nom tout trouvé pour la plus grosse planète du système solaire.", pts: 1 },
            { q: "Dans la mythologie grecque, quelle est la profession d'Orion ?", a: "Chasseur", d: "Zeus le transforma en un ensemble d'étoiles, face à la constellation du Taureau qu'il semble chasser éternellement, accompagné du Grand et du Petit Chien.", pts: 1 },
            { q: "Qui est Andromède ?", a: "Une princesse Ethiopienne", d: "Fille de Caphée et Cassiopé, victime de l'orgueil de sa mère elle est attachée à une pierre afin d'être dévorée par un monstre marin. Elle est sauvée de justesse par Persée.", pts: 2 },
            { q: "De quel mythe viendrait la forme de la constellation du Cygne ?", a: "De la métamorphose de Zeus", d: "Zeus se serait transformé en cygne blanc pour fuir ou séduire selon les versions de la légende (notamment celle de Léda).", pts: 2 },
            { q: "Parmi les 88 constellations officielles, seules 2 tirent leurs noms de personnes historique réelles. Lesquelles ?", a: "La Chevelure de Bérénice et l'Écu de Sobieski", d: "Bérénice II avait coupé sa magnifique chevelure pour l'offrir aux dieux. Lorsqu'elle disparut du temple, l'astronome de la cour expliqua au roi qu'Aphrodite l'avait transformée en constellation. L'écu est nommé après le roi de Pologne Jean III Sobieski, qui a remporté une grande bataille contre l'empire Ottoman en 1683", pts: 3 }
        ],
        "Pop Culture et Science-Fiction": [
            { q: "Dans les batailles spatiales de Star Wars, pourquoi les grosses explosions bruyantes sont-elles impossibles en réalité ?", a: "Le son ne se propage pas dans le vide", d: "Le son a besoin de matière (air, eau, solide) pour vibrer et se déplacer. L'espace est donc totalement silencieux.", pts: 1 },
            { q: "Dans le film Avatar, Pandora orbite autour d'une immense géante gazeuse. Qu'est donc scientifiquement Pandora ?", a: "Une exolune (ou lune)", d: "C'est un satellite naturel orbitant autour d'une autre planète.", pts: 1 },
            { q: "Dans Interstellar, le temps s'écoule beaucoup plus lentement sur la planète proche du trou noir. De quel concept physique s'agit-il ?", a: "La dilatation du temps", d: "Un champ gravitationnel immense déforme l'espace et le temps. Pour les astronautes, 1 heure s'écoule, alors que 7 ans passent sur Terre !", pts: 2 },
            { q: "Le film Gravity met en scène la destruction en chaîne de tous les satellites en orbite. Quel est le nom scientifique de ce scénario catastrophe ?", a: "Le syndrome de Kessler", d: "Si la quantité de débris spatiaux devient trop importante, chaque collision génère de nouveaux débris, rendant l'orbite terrestre impraticable.", pts: 2 },
            { q: "Dans Apollo 13 et Seul sur Mars, les vaisseaux utilisent la gravité d'un astre pour accélérer sans moteur. Comment s'appelle cette manœuvre ?", a: "L'assistance gravitationnelle (ou fronde gravitationnelle)", d: "La sonde s'approche d'une planète et récupère un tout petit peu de son énergie orbitale pour être catapultée plus loin et plus vite (en limitant la consommation de carburant).", pts: 3 }
        ]
    },
    phase3: [
        { q: "Je suis un petit corps de glace et de poussière célèbre pour ma forme surprenante de canard en plastique. En 2014, j'ai marqué l'histoire en devenant la toute première comète à accueillir un objet humain sur ma surface, le petit robot Philae. Qui suis-je ?", a: "La comète Tchouri (ou 67P/Tchourioumov-Guérassimenko)", d: "La sonde européenne Rosetta a voyagé pendant 10 ans pour la rejoindre. L'atterrissage de Philae a été très mouvementé : ses harpons n'ont pas fonctionné et il a rebondi pendant deux heures avant de s'immobiliser !", pts: 1 },
        { q: "Je suis une petite planète rocheuse, la plus dense de mon système. Vue de très loin, j'apparais comme un minuscule « point bleu pâle » flottant dans l'immensité de l'espace. À ce jour, je suis le seul havre de vie connu dans tout l'Univers. Qui suis-je ?", a: "La Terre", d: "La célèbre photo « Pale Blue Dot » a été prise par la sonde Voyager 1 en 1990 à 6 milliards de kilomètres de distance, sur une idée de l'astronome Carl Sagan.", pts: 1 },        
        { q: "Je suis la sonde spatiale humaine la plus éloignée de la Terre, et la première à avoir franchi l'héliosphère. Je transporte un disque en or gravé d'images et de sons terrestres pour d'éventuels extraterrestres. Qui suis-je ?", a: "Voyager 1", d: "Lancée en 1977, elle fonce aujourd'hui à plus de 24 milliards de kilomètres de la Terre, plongeant dans l'espace interstellaire.", pts: 2 },
        { q: "Je suis une immense pouponnière d'étoiles visible à l'œil nu depuis la Terre. Tache floue lumineuse située juste sous la ceinture du célèbre chasseur, je suis l'une des nébuleuses les plus photographiées par les astronomes amateurs. Qui suis-je ?", a: "La Nébuleuse d'Orion (M42)", d: "Elle est située à environ 1 350 années-lumière de la Terre. À l'intérieur, de très jeunes étoiles extrêmement chaudes illuminent le gaz qui les a vues naître.", pts: 2 },
        { q: "Je suis un très faible rayonnement électromagnétique, observable sous la forme de micro-ondes dans toutes les directions du ciel. Je suis la plus ancienne lumière de l'univers, résidu refroidi du Big Bang. Que suis-je ?", a: "Le fond diffus cosmologique (ou rayonnement fossile)", d: "Découvert par hasard en 1964 par deux ingénieurs (Penzias et Wilson) qui croyaient que le bruit constant de leur antenne était dû à des fientes de pigeons !", pts: 3 },
        { q: "Je suis une force mystérieuse dont la nature exacte échappe encore totalement aux astrophysiciens. Je représente à moi seule près de 68 % du cosmos et j'agis comme une force répulsive qui repousse les galaxies les unes des autres. Que suis-je ?", a: "L'énergie sombre (ou énergie noire)", d: "C'est elle qui est responsable de l'accélération de l'expansion de l'Univers. À ne surtout pas confondre avec la matière noire qui, au contraire, attire et maintient les galaxies ensemble !", pts: 3 }    ]
};