window.QUESTION_BANK = {
    phase1: [
        // 5 Faciles - Niveau Initié (1 pt)
        { q: "Quelle est la seule planète du Système solaire à avoir été découverte par des calculs mathématiques avant même d'être observée au télescope ?", a: "Neptune", d: "C'est l'astronome français Urbain Le Verrier qui a déduit sa position en étudiant les anomalies de l'orbite d'Uranus. On théorise qu'il y pleut des diamants !", pts: 1 },
        { q: "Quelle catégorie de corps célestes a été créée en 2006, entraînant le déclassement de Pluton ?", a: "Les planètes naines", d: "En plus de la taille, être une planète nécessite d'avoir fait le ménage dans son orbite, ce qui n'est pas le cas de Pluton ou Cérès.", pts: 1 },
        { q: "Quelle force régit le mouvement des planètes autour du Soleil ?", a: "La gravitation", d: "Théorisée par Isaac Newton en 1687, elle sera plus tard expliquée par Albert Einstein comme une déformation de l'espace-temps.", pts: 1 },
        { q: "Comment appelle-t-on une planète qui orbite autour d'une autre étoile ?", a: "Une exoplanète", d: "La toute première (51 Pegasi b) a été découverte en 1995 par deux astronomes suisses, Michel Mayor et Didier Queloz, ce qui leur a valu le prix Nobel en 2019 !", pts: 1 },
        { q: "Entre les orbites de quelles planètes se trouve la ceinture principale d'astéroïdes ?", a: "Entre Mars et Jupiter", d: "Elle contient des millions de fragments rocheux qui n'ont jamais pu former une planète, en particulier à cause de la force de gravité titanesque de Jupiter. On y trouve la planète naine Cérès.", pts: 1 },
        
        // 7 Moyennes (2 pts)
        { q: "Quelle est le nom de l'énorme tempête anticyclonique de l'on peut observer sur Jupiter ?", a: "La Grande Tache rouge", d: "Elle est observée depuis plusieurs siècles et est si gigantesque que l'on pourrait y faire entrer la Terre entière.", pts: 2 },
        { q: "Quel gaz compose majoritairement le Soleil ?", a: "L'hydrogène", d: "Le Soleil est composé à 73% d'hydrogène et 25% d'hélium. C'est la fusion de l'hydrogène en hélium qui produit son énergie.", pts: 2 },
        { q: "Quelle unité de mesure représente la distance Soleil-Terre ?", a: "L'unité astronomique", d: "Elle équivaut à environ 150 000 000 km. Pour ordre de grandeur, Neptune se situe à 30 UA et le nuage d'Oort s'étend jusqu'à 100 000 UA.", pts: 2 },
        { q: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", a: "Environ 8 minutes", d: "La lumière voyageant à environ 300 000 km/s, si le Soleil disparaissait, nous ne le saurions que 8 minutes plus tard.", pts: 2 },
        { q: "Quel effet physique permet de déduire que l'Univers est en expansion grâce au décalage vers le rouge ?", a: "L'effet Doppler", d: "C'est le même principe qui rend le son de la sirène d'une ambulance plus grave lorsqu'elle s'éloigne de nous.", pts: 2 },
        { q: "Quelle planète a pour satellites principaux Io, Europe, Ganymède et Callisto ?", a: "Jupiter", d: "Ce sont les 4 satellites galiléens, découverts par Galilée en 1610 avec sa lunette astronomique.", pts: 2 },
        { q: "Comment se nomme la limite autour d'un trou noir au-delà de laquelle rien ne peut s'échapper ?", a: "L'horizon des événements", d: "Une fois cette frontière franchie, la vitesse de libération devient supérieure à la vitesse de la lumière.", pts: 2 },
        
        // 3 Difficiles (3 pts)
        { q: "Comment appelle-t-on le type d'étoile extrêmement dense et tournant très vite sur elle-même ?", a: "Un pulsar (ou étoile à neutrons)", d: "La matière d'une étoile à neutrons est si condensée qu'elle a près de 2 fois la masse du soleil dans une sphère de 20 km.", pts: 3 },
        { q: "Lorsqu'une étoile massive arrive en fin de vie, la création de quel élément chimique dans son cœur précipite son explosion en supernova ?", a: "Le fer", d: "Contrairement aux éléments plus légers, la fusion du fer consomme plus d'énergie qu'elle n'en produit. Sans énergie pour contrer la gravité, l'étoile s'effondre sur elle-même.", pts: 3 },
        { q: "Quel effet optique, prédit par Albert Einstein, est causé par la courbure de l'espace-temps autour d'un amas massif déviant la lumière d'une galaxie d'arrière-plan ?", a: "Une lentille gravitationnelle", d: "Cet effet agit comme une loupe cosmique, permettant aux astronomes de voir des objets situés beaucoup plus loin.", pts: 3 }
    ],
phase2: {
        "Le système solaire": [
            { q: "Quelle planète est surnommée la planète rouge à cause de l'oxyde de fer (rouille) à sa surface ?", a: "Mars", d: "Planète ayant potentiellement abritée de l'au liquide à sa surface, il y fait maintenant très froid avec une moyenne de -63°C à l'équateur.", pts: 1 },
            { q: "Quelle planète est célèbre pour son système d'anneaux très brillant et visible, principalement composé de glace et de roche ?", a: "Saturne", d: "Ses anneaux sont si fins par rapport à leur largeurs (quelques dizaines de mètres d'épaisseur pour ~400 000km de large) que, vus de la tranche, ils disparaissent presque complètement.", pts: 1 },
            { q: "Contrairement aux autres planètes, quelle planète tourne sur elle-même dans le sens inverse (d'est en ouest) ?", a: "Vénus", d: "Sur Vénus, le Soleil se lève à l'ouest et se couche à l'est. Elle tourne aussi si lentement qu'une journée est plus longue qu'une année (224 jours pour tourner autour du soleil mais 243 pour tourner autour d'elle même) !", pts: 2 },
            { q: "Quel gaz compose majoritairement le Soleil ?", a: "L'hydrogène", d: "Le Soleil est composé d'environ 73% d'hydrogène et 25% d'hélium. C'est la fusion de l'hydrogène en hélium qui produit son énergie.", pts: 2 },
            { q: "Comment appelle-t-on la limite de la sphère d'influence du vent solaire, là où il s'arrête face au milieu interstellaire ?", a: "L'héliopause", d: "Néanmoins elle ne marque pas forcément la frontière du système solaire, en effet après l'héliopose (située à environ 120 UA) se trouverai le nuage d'Oort, un nuage hypothétique composé de milliards de corps glacés, il s'étendrai de 2000 UA jusqu'à 50 000 à 100 000 UA.", pts: 3 }
        ],
        "Lunes, Astéroïdes et Comètes": [
            { q: "Entre les orbites de quelles planètes se trouve la ceinture principale d'astéroïdes ?", a: "Entre Mars et Jupiter", d: "Elle contient des millions de fragments rocheux qui n'ont jamais pu former une planète, en particulier à cause de la gravité de Jupiter.", pts: 1 },
            { q: "Quelle est la principale différence de composition entre un astéroïde et une comète ?", a: "La comète contient de la glace", d: "C'est en partie cette glace qui, en se sublimant à l'approche du Soleil, forme la célèbre chevelure et la queue des comètes.", pts: 1 },
            { q: "Quelle est la plus grande lune du Système solaire ?", a: "Ganymède", d: "Ce satellite de Jupiter est plus grand que la planète Mercure. C'est aussi la seule lune connue à posséder son propre champ magnétique.", pts: 2 },
            { q: "Comment s'appelle le grand anneau de corps glacés situé au-delà de l'orbite de Neptune ?", a: "La ceinture de Kuiper", d: "Elle est similaire à la ceinture d'astéroïdes mais 20 fois plus large, et contient également les restes de la formation du Système solaire. On y trouve de nombreuses planètes naines comme Pluton ou Eris", pts: 2 },
            { q: "En astronomie, qu'est-ce qu'un astéroïde troyen ?", a: "Un astéroïde qui partage la même orbite qu'une planète", d: "Ils sont piégés dans les points de Lagrange L4 et L5 (zones de stabilité gravitationnelle) en avant ou en arrière de la planète. Les plus connus sont ceux de Jupiter qui en possède des milliers, mais la Terre en possède également 2 connus à ce jour.", pts: 3 }
        ],
        "Exoplanètes et Astrobiologie": [
            { q: "Comment appelle-t-on une planète qui tourne autour d'une autre étoile ?", a: "Une exoplanète", d: "La toute première a été découverte en 1995 par les astronomes suisses Michel Mayor et Didier Queloz. Elle orbite autour de l'étoile 51 Pegasi b.", pts: 1 },
            { q: "Comment s'appelle la zone théorique autour d'une étoile où la température permettrait d'avoir de l'eau liquide ?", a: "La zone habitable", d: "Être dans cette zone ne garantit pas la vie (la Lune y est, mais n'a pas d'eau liquide), mais c'est un très bon point de départ pour les recherches d'eau liquide et donc, de potentielles formes de vie.", pts: 1 },
            { q: "Quelle méthode est la méthode de détection d'exoplanète la plus efficace à ce jour ?", a: "La méthode des transits", d: "Elle consiste à observer les faibles baisses de luminosité de l'étoile quand la planète passe devant.", pts: 2 },
            { q: "Quel petit animal microscopique terrestre est célèbre pour sa capacité à survivre dans le vide de l'espace ?", a: "Le tardigrade", d: "Il peut se déshydrater presque totalement, ralentir très fortement son métabolisme et remplacer ses cellules pour résister au vide, aux radiations et aux températures extrêmes. Cet état est appelé Cryptobiose", pts: 2 },
            { q: "Quel système planétaire, situé à environ 40 années-lumière, est devenu célèbre pour abriter 7 planètes de taille terrestre, dont 3 en zone habitable ?", a: "TRAPPIST-1", d: "Elles orbitent autour d'une étoile naine rouge ultra-froide, et sont l'une des cibles principales du télescope James Webb.", pts: 3 }
        ], 
        "Étoiles et Constellations": [
            { q: "Comment s'appelle l'étoile qui indique toujours le nord dans l'hémisphère nord ?", a: "L'étoile polaire", d: "Elle ne bouge pas car elle est située presque exactement dans le prolongement de l'axe de rotation de la Terre.", pts: 1 },
            { q: "Quelle constellation est célèbre pour sa forme de grande Casserole ?", a: "La Grande Ourse", d: "La casserole, composée de 7 étoiles, n'est en fait qu'une partie (un astérisme) de la constellation complète.", pts: 1 },
            { q: "Quel nom donne-t-on aux trois étoiles alignées qui forment la ceinture de la constellation d'Orion ?", a: "Les Trois Rois (ou les trois mages)", d: "Leurs véritables noms astronomiques sont Alnitak, Alnilam et Mintaka.", pts: 2 },
            { q: "A quelle distance du soleil se trouve Proxima du Centaure, l'étoile la plus proche du soleil ?", a: "~4,2 années-lumières", d: "Elle est située à environ 4,2 années-lumière. Malgré sa proximité spatiale, c'est une naine rouge impossible à voir à l'œil nu.", pts: 2 },
            { q: "Dans le classment des étoiles par type spectral (O, B, A, F, G, K, M), à quelle catégorie appartient notre Soleil ?", a: "Le type G (Naine jaune)", d: "Les étoiles O sont les plus chaudes et bleues, tandis que les M sont les plus froides et rouges. Le Soleil est une étoile moyenne de type G2V.", pts: 3 }
        ],
        "Ciel profond": [
            { q: "Quel est le nom de la galaxie spirale dans laquelle nous nous trouvons ?", a: "La Voie lactée", d: "Vue de la Terre depuis un ciel très sombre, elle ressemble à une traînée de lait étalée dans le ciel, d'où son nom.", pts: 1 },
            { q: "Comment appelle-t-on l'explosion gigantesque qui marque la fin de vie d'une étoile massive ?", a: "Une supernova", d: "Durant cette explosion, l'étoile peut briller temporairement plus fort que toutes les autres étoiles de sa galaxie réunies.", pts: 1 },
            { q: "Comment se nomme la limite immatérielle autour d'un trou noir au-delà de laquelle rien ne peut s'échapper, même la lumière ?", a: "L'horizon des événements", d: "Une fois cette frontière franchie, la vitesse de libération devient supérieure à la vitesse de la lumière (environ 300 000 km/s).", pts: 2 },
            { q: "Avec quelle galaxie voisine la Voie lactée va-t-elle fusionner dans environ 4 milliards d'années ?", a: "La galaxie d'Andromède (ou M31)", d: "C'est l'objet le plus lointain observable à l'œil nu depuis la Terre.", pts: 2 },
            { q: "Comment appelle-t-on la toute première lumière émise par l'Univers, encore détectable aujourd'hui sous forme de micro-ondes ?", a: "Le fond diffus cosmologique (ou rayonnement fossile)", d: "C'est l'écho du Big Bang, émis environ 380 000 ans après la naissance de l'Univers lorsque celui-ci est devenu transparent.", pts: 3 }
        ],
        "Mécanique Céleste et Phénomènes": [
            { q: "Lors d'une éclipse solaire, quel astre vient se placer exactement entre la Terre et le Soleil ?", a: "La Lune", d: "Le hasard fait que la Lune est 400 fois plus petite que le Soleil, mais aussi 400 fois plus proche, ce qui leur donne la même taille apparente.", pts: 1 },
            { q: "Qu'est-ce qu'une étoile filante en réalité ?", a: "Un débris rocheux qui brûle dans l'atmosphère (météore)", d: "La friction extrême avec l'air à haute vitesse vaporise l'astéroïde, créant la traînée lumineuse que l'on appelle un météore.", pts: 1 },
            { q: "Quel astre est le principal responsable du phénomène des marées océaniques sur Terre ?", a: "La Lune", d: "Son attraction gravitationnelle tire les océans, créant des bosses d'eau qui parcourent le globe avec la rotation terrestre, créant les marées hautes.", pts: 2 },
            { q: "Comment appelle-t-on le point de l'orbite où la Terre est la plus proche du soleil ?", a: "Le périhélie", d: "Paradoxalement pour nous, la Terre passe au périhélie au début du mois de janvier ! Cela prouve bien que la distance Terre-Soleil n'est pas ce qui crée les saisons, c'est l'inclinaison de la Terre.", pts: 2 },
            { q: "Qu'est-ce qui provoque les aurores boréales et australes sur Terre ?", a: "Les particules du vent solaire déviées par le champ magnétique", d: "Le bouclier magnétique terrestre ramène ces particules chargées vers les pôles, où elles ionisent les gaz de notre atmosphère qui se mettent à briller.", pts: 3 }
        ],
        "Matériel et Astrophotographie": [ // A POURSUIVRE ICI
            { q: "Comment s'appelle le célèbre télescope spatial de la NASA lancé en 1990 ?", a: "Hubble", d: "Il a offert des images historiques car, étant dans l'espace, il n'est pas gêné par les perturbations de l'atmosphère terrestre.", pts: 1 },
            { q: "Quelle est la différence fondamentale de conception entre une lunette astronomique et un télescope ?", a: "La lunette utilise des lentilles, le télescope des miroirs", d: "Les lunettes fonctionnent par réfraction de la lumière, tandis que les télescopes fonctionnent par réflexion.", pts: 1 },
            { q: "Quel type de monture mécanique permet de suivre facilement un astre en compensant la rotation de la Terre ?", a: "La monture équatoriale", d: "Une fois alignée avec l'étoile polaire, il suffit de tourner un seul axe pour annuler le mouvement du ciel.", pts: 2 },
            { q: "En optique, que calcule-t-on en divisant la longueur focale par le diamètre de l'instrument ?", a: "Le rapport F/D (rapport d'ouverture)", d: "Un rapport F/D court (ex: f/4) est très « lumineux » et adapté au ciel profond, un long (f/10) est souvent utilisé pour le planétaire.", pts: 2 },
            { q: "Dans une lunette de mauvaise qualité, quel nom donne-t-on aux halos colorés baveux autour des étoiles ?", a: "L'aberration chromatique", d: "Les lentilles simples ne focalisent pas toutes les couleurs exactement au même endroit. On corrige cela avec des objectifs dits apochromatiques.", pts: 3 }
        ],
        "Missions Historiques": [
            { q: "En quelle année ont eu lieu les premiers pas de l'Homme sur la Lune avec Apollo 11 ?", a: "1969", d: "Neil Armstrong et Buzz Aldrin ont marché sur la surface lunaire, pendant que Michael Collins restait en orbite.", pts: 1 },
            { q: "Qui est le tout premier être humain à être allé dans l'espace ?", a: "Youri Gagarine", d: "Le cosmonaute soviétique a décollé à bord de la capsule Vostok 1 en 1961 et a fait un tour de la Terre.", pts: 1 },
            { q: "Comment s'appelait le premier satellite artificiel lancé par l'Homme en 1957 ?", a: "Spoutnik 1", d: "Cette petite sphère soviétique avec 4 antennes émettait un simple « bip-bip » radio qui a déclenché la course à l'espace.", pts: 2 },
            { q: "Qui fut la première femme à voler dans l'espace en 1963 ?", a: "Valentina Terechkova", d: "Cette cosmonaute soviétique a effectué 48 orbites autour de la Terre à bord de Vostok 6.", pts: 2 },
            { q: "Quel programme spatial a réussi, dans les années 70 et 80, à poser les seules et uniques sondes sur la surface infernale de Vénus ?", a: "Le programme Venera (Union Soviétique)", d: "Malgré 460°C et une pression écrasante, ces sondes ont survécu jusqu'à 2 heures et envoyé les seules photos du sol vénusien.", pts: 3 }
        ],
        "Missions Modernes": [
            { q: "Quel est le nom générique donné aux petits véhicules motorisés à roues qui explorent le sol martien ?", a: "Des rovers (ou astromobiles)", d: "Curiosity et Perseverance, toujours en activité, sont les rovers de la NASA les plus connus aujourd'hui.", pts: 1 },
            { q: "Quel nouveau télescope spatial, reconnaissable à son miroir doré en nids d'abeille, a été lancé fin 2021 ?", a: "Le James Webb Space Telescope (JWST)", d: "Spécialisé dans l'infrarouge, il regarde à travers la poussière pour voir les toute premières galaxies de l'Univers.", pts: 1 },
            { q: "Quelle sonde de la NASA a exploré de manière spectaculaire la planète Saturne et ses anneaux de 2004 à 2017 ?", a: "Cassini", d: "La sonde s'est sabordée en plongeant dans l'atmosphère de Saturne pour éviter de s'écraser sur une lune habitable comme Encelade.", pts: 2 },
            { q: "Comment s'appelle le petit hélicoptère de la NASA qui a réussi le premier vol motorisé sur une autre planète (Mars) en 2021 ?", a: "Ingenuity", d: "Prévu pour 5 vols de test, ce formidable petit engin en a finalement accompli 72 avant d'endommager ses pales !", pts: 2 },
            { q: "Quelle sonde européenne a réalisé l'exploit de se placer en orbite autour de la comète Tchouri en 2014 et d'y lâcher l'atterrisseur Philae ?", a: "Rosetta", d: "Elle a prouvé, entre autres, que l'eau des comètes comme Tchouri n'a pas la même signature chimique que l'eau des océans terrestres.", pts: 3 }
        ],
        "Histoire de l'astronomie": [
            { q: "Quel physicien a formulé en 1687 la loi de la gravitation universelle (souvent associée à la chute d'une pomme) ?", a: "Isaac Newton", d: "Il a prouvé que la force qui fait tomber les objets sur Terre est la même que celle qui maintient la Lune en orbite.", pts: 1 },
            { q: "Quel savant italien a braqué pour la première fois une lunette d'approche vers le ciel en 1609 ?", a: "Galilée", d: "Il y a découvert les cratères de la Lune, les taches solaires et les 4 grosses lunes de Jupiter (Io, Europe, Ganymède, Callisto).", pts: 1 },
            { q: "Qui a formulé mathématiquement la théorie de l'héliocentrisme (la Terre tourne autour du Soleil) en 1543 ?", a: "Nicolas Copernic", d: "Son ouvrage a révolutionné la science, bien qu'il ait repoussé sa publication jusqu'à la fin de sa vie par peur des représailles.", pts: 2 },
            { q: "Quel mathématicien allemand a découvert que les orbites des planètes ne sont pas des cercles parfaits, mais des ellipses ?", a: "Johannes Kepler", d: "Ses fameuses trois lois de Kepler (publiées entre 1609 et 1619) sont toujours utilisées aujourd'hui pour calculer les orbites.", pts: 2 },
            { q: "Quelle astronome américaine a apporté dans les années 1970 les premières preuves de l'existence de la matière noire ?", a: "Vera Rubin", d: "En étudiant la vitesse de rotation des galaxies, elle a compris qu'elles contenaient beaucoup plus de matière que ce qu'on pouvait observer.", pts: 3 }
        ],
        "Mythes et Légendes du ciel": [
            { q: "Dans la mythologie romaine, Jupiter est le roi des dieux. Quel est son nom dans la mythologie grecque ?", a: "Zeus", d: "C'est le dieu du ciel et de la foudre. Un nom approprié pour la plus majestueuse des planètes gazeuses de notre système.", pts: 1 },
            { q: "Dans la mythologie grecque, quelle est la profession d'Orion, qui justifie qu'il soit entouré par le Grand Chien et le Petit Chien ?", a: "Chasseur", d: "Zeus le transforma en un ensemble d'étoiles, face à la constellation du Taureau qu'il semble chasser éternellement.", pts: 1 },
            { q: "Quelle planète tient son nom du dieu de la guerre, en raison de sa couleur rouge rappelant le sang ?", a: "Mars (ou Arès chez les Grecs)", d: "Ses deux lunes, Phobos et Deimos, portent les noms des enfants d'Arès signifiant respectivement la Panique et la Terreur.", pts: 2 },
            { q: "De quel mythe viendrait la forme de la constellation du Cygne ?", a: "De la métamorphose de Zeus", d: "Zeus se serait transformé en cygne blanc pour fuir ou séduire selon les versions de la légende (notamment celle de Léda).", pts: 2 },
            { q: "Dans la mythologie grecque, le dieu Ouranos est la personnification du Ciel étoilé. À quelle planète a-t-il donné son nom ?", a: "Uranus", d: "Uranus est d'ailleurs la seule planète du Système solaire dont le nom est tiré directement de la mythologie grecque et non romaine.", pts: 3 }
        ],
        "Pop Culture et Science-Fiction": [
            { q: "Dans les batailles spatiales de Star Wars, pourquoi les grosses explosions bruyantes sont-elles impossibles en réalité ?", a: "Le son ne se propage pas dans le vide", d: "Le son a besoin de matière (air, eau, solide) pour vibrer et se déplacer. L'espace est totalement silencieux.", pts: 1 },
            { q: "Dans le film Avatar, Pandora orbite autour d'une immense géante gazeuse. Qu'est donc scientifiquement Pandora ?", a: "Une exolune (ou lune)", d: "C'est un satellite naturel orbitant autour d'une autre planète. Dans notre propre système, les astronomes espèrent y trouver de la vie (Europe, Encelade).", pts: 1 },
            { q: "Dans Interstellar, le temps s'écoule beaucoup plus lentement sur la planète proche du trou noir. De quel concept physique d'Einstein s'agit-il ?", a: "La dilatation du temps", d: "Un champ gravitationnel immense déforme l'espace et le temps. Pour les astronautes, 1 heure s'écoule, alors que 7 ans passent sur Terre !", pts: 2 },
            { q: "Le film Gravity met en scène la destruction en chaîne de tous les satellites en orbite. Quel est le nom scientifique de ce scénario catastrophe ?", a: "Le syndrome de Kessler", d: "Si la quantité de débris spatiaux devient trop importante, chaque collision génère de nouveaux débris, rendant l'orbite terrestre impraticable.", pts: 2 },
            { q: "Dans Apollo 13 et Seul sur Mars, les vaisseaux utilisent la gravité d'un astre pour accélérer sans moteur. Comment s'appelle cette manœuvre ?", a: "L'assistance gravitationnelle (ou fronde gravitationnelle)", d: "La sonde s'approche d'une planète et « vole » un tout petit peu de son énergie orbitale pour être catapultée plus loin et plus vite.", pts: 3 }
        ]
    },
    phase3: [
        { q: "Je suis le petit robot à six roues de la NASA qui explore le cratère Jezero sur Mars depuis 2021. Je suis accompagné du mini-hélicoptère Ingenuity. Qui suis-je ?", a: "Perseverance", d: "Il est spécialement conçu pour chercher des signes de vie ancienne et préparer des échantillons qui seront rapportés sur Terre.", pts: 1 },
        { q: "Je suis une petite planète naine glacée, située dans la lointaine ceinture de Kuiper. Rétrogradée en 2006, la sonde New Horizons m'a photographiée avec un grand cœur blanc sur ma surface en 2015. Qui suis-je ?", a: "Pluton", d: "Son déclassement a fait scandale, mais était nécessaire suite à la découverte de nombreux autres corps de même taille (comme Eris) dans son voisinage.", pts: 1 },
        { q: "Je suis le premier satellite artificiel de la Terre. Sphère en aluminium dotée de quatre grandes antennes, j'ai été lancé en octobre 1957. Qui suis-je ?", a: "Spoutnik 1", d: "Lancé par l'Union Soviétique, mon célèbre « bip-bip » entendu à la radio a effrayé les Américains et a lancé la course à l'espace.", pts: 2 },
        { q: "Je suis la sonde spatiale humaine la plus éloignée de la Terre, et la première à avoir franchi l'héliosphère. Je vais atteindre prochainement 1 jour-lumière de la terre. Je transporte un disque en or gravé pour d'éventuels extraterrestres. Qui suis-je ?", a: "Voyager 1", d: "Lancée en 1977, elle fonce aujourd'hui à plus de 24 milliards de kilomètres de la Terre dans l'espace interstellaire.", pts: 2 },
        { q: "Je suis un très faible rayonnement électromagnétique, observable sous la forme de micro-ondes dans toutes les directions du ciel. Je suis la plus ancienne lumière de l'univers, résidu refroidi du Big Bang. Que suis-je ?", a: "Le fond diffus cosmologique (ou rayonnement fossile)", d: "Découvert par hasard en 1964 par deux ingénieurs (Penzias et Wilson) qui croyaient que le bruit de leur antenne était dû à des fientes de pigeons !", pts: 3 }
    ]
};